version: '3'


servides:
  traefik:
    image: traefik
    ports:
        - "8080:8080"
        - "80:80"
    volumes:
      - $PWD/traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    image: nginx
    labels:
      - "traefik.frontend.rule=Host:server.docker.local"
      - "traefik.enable=true"
    ports:
      - "8081:80"
